/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego1;

/**
 *
 * @author kikal
 */
public class Interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz2
     */
    public Interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        txtP3 = new javax.swing.JTextField();
        txtP4 = new javax.swing.JTextField();
        txtP5 = new javax.swing.JTextField();
        txtP6 = new javax.swing.JTextField();
        txtP7 = new javax.swing.JTextField();
        txtP8 = new javax.swing.JTextField();
        txtP9 = new javax.swing.JTextField();
        txtP10 = new javax.swing.JTextField();
        txtP11 = new javax.swing.JTextField();
        txtP12 = new javax.swing.JTextField();
        txtP14 = new javax.swing.JTextField();
        txtP15 = new javax.swing.JTextField();
        btnPuntoComa = new javax.swing.JButton();
        btnPara = new javax.swing.JButton();
        btnParentesisA = new javax.swing.JButton();
        btnParentesisC = new javax.swing.JButton();
        btnNumero = new javax.swing.JButton();
        btnTDato = new javax.swing.JButton();
        btnLlaveA = new javax.swing.JButton();
        btnPuntoComa2 = new javax.swing.JButton();
        btnIncremento = new javax.swing.JButton();
        btnSentencia = new javax.swing.JButton();
        btnPuntoComa3 = new javax.swing.JButton();
        txtP13 = new javax.swing.JTextField();
        btnComprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sintaxis Para", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Completa la sintaxis que se usa para un ciclo para");

        txtP1.setEditable(false);
        txtP1.setBackground(new java.awt.Color(153, 153, 255));
        txtP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP2.setEditable(false);
        txtP2.setBackground(new java.awt.Color(153, 153, 255));
        txtP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP2.setText("(");

        txtP3.setEditable(false);
        txtP3.setBackground(new java.awt.Color(153, 153, 255));
        txtP3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP3.setText("entero");

        txtP4.setEditable(false);
        txtP4.setBackground(new java.awt.Color(153, 153, 255));
        txtP4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP4.setText("=");

        txtP5.setEditable(false);
        txtP5.setBackground(new java.awt.Color(153, 153, 255));
        txtP5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP6.setEditable(false);
        txtP6.setBackground(new java.awt.Color(153, 153, 255));
        txtP6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP7.setEditable(false);
        txtP7.setBackground(new java.awt.Color(153, 153, 255));
        txtP7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP7.setText("veradero");

        txtP8.setEditable(false);
        txtP8.setBackground(new java.awt.Color(153, 153, 255));
        txtP8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP9.setEditable(false);
        txtP9.setBackground(new java.awt.Color(153, 153, 255));
        txtP9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP9.setText("x");

        txtP10.setEditable(false);
        txtP10.setBackground(new java.awt.Color(153, 153, 255));
        txtP10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP11.setEditable(false);
        txtP11.setBackground(new java.awt.Color(153, 153, 255));
        txtP11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP12.setEditable(false);
        txtP12.setBackground(new java.awt.Color(153, 153, 255));
        txtP12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP14.setEditable(false);
        txtP14.setBackground(new java.awt.Color(153, 153, 255));
        txtP14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtP15.setEditable(false);
        txtP15.setBackground(new java.awt.Color(153, 153, 255));
        txtP15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtP15.setText("}");

        btnPuntoComa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPuntoComa.setText(";");
        btnPuntoComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoComaActionPerformed(evt);
            }
        });

        btnPara.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPara.setText("para");
        btnPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaActionPerformed(evt);
            }
        });

        btnParentesisA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnParentesisA.setText("(");
        btnParentesisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesisAActionPerformed(evt);
            }
        });

        btnParentesisC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnParentesisC.setText(")");
        btnParentesisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesisCActionPerformed(evt);
            }
        });

        btnNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNumero.setText("1");
        btnNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroActionPerformed(evt);
            }
        });

        btnTDato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTDato.setText("doble");
        btnTDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDatoActionPerformed(evt);
            }
        });

        btnLlaveA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLlaveA.setText("{");
        btnLlaveA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlaveAActionPerformed(evt);
            }
        });

        btnPuntoComa2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPuntoComa2.setText(";");
        btnPuntoComa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoComa2ActionPerformed(evt);
            }
        });

        btnIncremento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIncremento.setText("++");
        btnIncremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrementoActionPerformed(evt);
            }
        });

        btnSentencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSentencia.setText("sentencia");
        btnSentencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentenciaActionPerformed(evt);
            }
        });

        btnPuntoComa3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPuntoComa3.setText(";");
        btnPuntoComa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoComa3ActionPerformed(evt);
            }
        });

        txtP13.setEditable(false);
        txtP13.setBackground(new java.awt.Color(153, 153, 255));

        btnComprobar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComprobar.setText("COMPROBAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtP14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnComprobar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtP9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtP10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtP11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtP12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtP13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(674, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPuntoComa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPara, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(btnParentesisA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParentesisC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTDato, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLlaveA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPuntoComa2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSentencia)
                .addGap(18, 18, 18)
                .addComponent(btnPuntoComa3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtP14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtP15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPuntoComa)
                    .addComponent(btnPara)
                    .addComponent(btnParentesisA)
                    .addComponent(btnParentesisC)
                    .addComponent(btnNumero)
                    .addComponent(btnTDato)
                    .addComponent(btnLlaveA)
                    .addComponent(btnPuntoComa2)
                    .addComponent(btnIncremento)
                    .addComponent(btnSentencia)
                    .addComponent(btnPuntoComa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnComprobar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Sintaxis para");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPuntoComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoComaActionPerformed
        // TODO add your handling code here:
        String palabra1 = ";";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra1);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra1);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra1);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra1);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra1);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra1);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra1);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra1);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra1);
        }
        btnPuntoComa.setEnabled(false);
    }//GEN-LAST:event_btnPuntoComaActionPerformed

    private void btnParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaActionPerformed
        // TODO add your handling code here:
        String palabra2 = "para";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra2);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra2);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra2);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra2);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra2);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra2);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra2);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra2);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra2);
        }
        btnPara.setEnabled(false);
    }//GEN-LAST:event_btnParaActionPerformed

    private void btnParentesisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesisAActionPerformed
        // TODO add your handling code here:
        String palabra3 = "(";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra3);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra3);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra3);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra3);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra3);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra3);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra3);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra3);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra3);
        }
        btnParentesisA.setEnabled(false);
    }//GEN-LAST:event_btnParentesisAActionPerformed

    private void btnParentesisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesisCActionPerformed
        // TODO add your handling code here:
        String palabra4 = ")";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra4);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra4);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra4);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra4);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra4);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra4);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra4);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra4);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra4);
        }
        btnParentesisC.setEnabled(false);
    }//GEN-LAST:event_btnParentesisCActionPerformed

    private void btnNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroActionPerformed
        // TODO add your handling code here:
        String palabra5 = "1";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra5);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra5);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra5);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra5);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra5);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra5);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra5);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra5);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra5);
        }
        btnNumero.setEnabled(false);
    }//GEN-LAST:event_btnNumeroActionPerformed

    private void btnTDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDatoActionPerformed
        // TODO add your handling code here:
        String palabra6 = "doble";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra6);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra6);
        }else if(txtP3.getText().length()==0){
            txtP6.setText(palabra6);
        }else if(txtP4.getText().length()==0){
            txtP8.setText(palabra6);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra6);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra6);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra6);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra6);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra6);
        }
        btnTDato.setEnabled(false);
    }//GEN-LAST:event_btnTDatoActionPerformed

    private void btnLlaveAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlaveAActionPerformed
        // TODO add your handling code here:
        String palabra7 = "{";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra7);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra7);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra7);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra7);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra7);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra7);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra7);
        }else if(txtP12.getText().length()==0){
            txtP13.setText(palabra7);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra7);
        }
        btnLlaveA.setEnabled(false);
    }//GEN-LAST:event_btnLlaveAActionPerformed

    private void btnPuntoComa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoComa2ActionPerformed
        // TODO add your handling code here:
        String palabra8 = ";";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra8);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra8);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra8);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra8);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra8);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra8);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra8);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra8);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra8);
        }
        btnPuntoComa2.setEnabled(false);
    }//GEN-LAST:event_btnPuntoComa2ActionPerformed

    private void btnIncrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrementoActionPerformed
        // TODO add your handling code here:
        String palabra9 = "++";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra9);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra9);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra9);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra9);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra9);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra9);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra9);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra9);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra9);
        }
        btnIncremento.setEnabled(false);
    }//GEN-LAST:event_btnIncrementoActionPerformed

    private void btnSentenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentenciaActionPerformed
        // TODO add your handling code here:
        String palabra10 = "sentencia";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra10);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra10);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra10);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra10);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra10);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra10);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra10);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra10);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra10);
        }
        btnSentencia.setEnabled(false);
    }//GEN-LAST:event_btnSentenciaActionPerformed

    private void btnPuntoComa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoComa3ActionPerformed
        // TODO add your handling code here:
        String palabra11 = ";";
        
        if(txtP1.getText().length()==0){
            txtP1.setText(palabra11);
        }else if(txtP5.getText().length()==0){
            txtP5.setText(palabra11);
        }else if(txtP6.getText().length()==0){
            txtP6.setText(palabra11);
        }else if(txtP8.getText().length()==0){
            txtP8.setText(palabra11);
        }else if(txtP10.getText().length()==0){
            txtP10.setText(palabra11);
        }else if(txtP11.getText().length()==0){
            txtP11.setText(palabra11);
        }else if(txtP12.getText().length()==0){
            txtP12.setText(palabra11);
        }else if(txtP13.getText().length()==0){
            txtP13.setText(palabra11);
        }else if(txtP14.getText().length()==0){
            txtP14.setText(palabra11);
        }
        btnPuntoComa3.setEnabled(false);
    }//GEN-LAST:event_btnPuntoComa3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnIncremento;
    private javax.swing.JButton btnLlaveA;
    private javax.swing.JButton btnNumero;
    private javax.swing.JButton btnPara;
    private javax.swing.JButton btnParentesisA;
    private javax.swing.JButton btnParentesisC;
    private javax.swing.JButton btnPuntoComa;
    private javax.swing.JButton btnPuntoComa2;
    private javax.swing.JButton btnPuntoComa3;
    private javax.swing.JButton btnSentencia;
    private javax.swing.JButton btnTDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP10;
    private javax.swing.JTextField txtP11;
    private javax.swing.JTextField txtP12;
    private javax.swing.JTextField txtP13;
    private javax.swing.JTextField txtP14;
    private javax.swing.JTextField txtP15;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP3;
    private javax.swing.JTextField txtP4;
    private javax.swing.JTextField txtP5;
    private javax.swing.JTextField txtP6;
    private javax.swing.JTextField txtP7;
    private javax.swing.JTextField txtP8;
    private javax.swing.JTextField txtP9;
    // End of variables declaration//GEN-END:variables
}
